### ISSUE TITLE
difference in census API state totals and state's county totals

### ISSUE THREAD

**Issue by nazanin-tabatabaei** [modelearth/community#9]
The last block of this [notebook](../blob/master/info/data/data_collection.ipynb) contains the code for generating the state-wide data.
If you know why the US census API state totals are less than the sum of each state’s county totals, please post an issue to tell us.

**Comment by WesIngwersen** [comment]
@nazanin-tabatabaei, The reason that county totals often do not match state totals in the Census data is because of non disclosure of data at the county level when there may only be 1-2 entities operating there and it can infringe on their privacy @catherinebirney can explain to you more and how we handle this in [flowsa](https://github.com/USEPA/flowsa)

**Comment by catherinebirney** [comment]
@nazanin-tabatabaei  @WesIngwersen  Right now, we've simply noted that there are data suppressions at the county level, we haven't written any code to try to estimate the suppressions. 

Typically, the sum of the county level data is less than or equal to published state level data. If your summed county totals are greater than published state values, I'd guess data is being double counted.

**Comment by nazanin-tabatabaei** [comment]
There are two ways to get statewide data.

1.one way is to get it from the county-level api call, which comes with some state-level data as well. ( what I was using previously).

2. The second way is to get the state-level data, by making api calls, correctly formated for state-level data (instead of county-level data.) 

The second approach gave me values that are very close to the aggregation of county-level data. As @WesIngwersen  and @catherinebirney mentioned, the sum of the county-level data is slightly less than or equal to published state-level data.

Thank you for your help and clarification.
